project_id = "vsevsjvtrshgeiudrnth"

[functions.submit-contact]
verify_jwt = false

[functions.get-telegram-user]
verify_jwt = false

[functions.setup-telegram-webhook]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.create-payment-order-ankit]
verify_jwt = false

[functions.create-payment-order-artcreate]
verify_jwt = false

[functions.create-payment-order-codelive]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.cashfree-webhook]
verify_jwt = false