project_id = "vsevsjvtrshgeiudrnth"

[functions.submit-contact]
verify_jwt = false

[functions.get-telegram-user]
verify_jwt = false

[functions.setup-telegram-webhook]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.generate-obs-token]
verify_jwt = false

[functions.notify-moderators-ankit]
verify_jwt = false

[functions.obs-alerts-ws]
verify_jwt = false

[functions.ankit-obs-alerts]
verify_jwt = false